<a href="https://colab.research.google.com/github/SohamIITK/Physics-Extras/blob/main/PHY461_Expt.30_Ge_using_Two_probes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

l = 1e-3
A = 2e-4

In [ ]:
I = 10e-3
T = np.array([25, 37, 49, 62, 74, 86, 98, 110, 122, 124, 125])
T = T + 273
print(T)
print(np.round(1000/T, 3))

[298 310 322 335 347 359 371 383 395 397 398]
[3.356 3.226 3.106 2.985 2.882 2.786 2.695 2.611 2.532 2.519 2.513]


In [ ]:
V = np.array([2.353, 2.182, 1.964, 1.769, 1.502, 1.289, 1.120, 0.981, 0.623])

cond = I*l/(V*A)
print(np.round(cond,3))

[0.011 0.011 0.013 0.014 0.017 0.019 0.022 0.025 0.04 ]


In [ ]:
V1 = np.array([0.746, 0.919, 1.416, 1.698, 2.018, 2.400, 2.814])

cond1 = I*l/(V1*A)
print(np.round(cond1,3))

[0.034 0.027 0.018 0.015 0.012 0.01  0.009]


In [ ]:
eg = 1.738 * 2000 * 1.38 * 10**-23
eg = eg/(1.6e-19)
print(eg)

0.29980499999999993
